name: tests

on:
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: pip install -r requirements-dev.txt
      - name: Test
        run: pytest
